services:
  - type: web
    name: agent-mira-frontend
    env: node
    region: singapore
    rootDir: .
    buildCommand: cd case-study-B-ml-recommender/frontend-react && npm install && npm run build
    startCommand: cd case-study-B-ml-recommender/frontend-react && npx serve -s dist -l $PORT
    envVars:
      - key: VITE_BACKEND_BASE
        fromService:
          name: agent-mira-backend
          type: web
          property: url
