services:
  - type: web
    name: agent-mira-frontend
    env: node
    region: singapore
    rootDir: case-study-B-ml-recommender/frontend-react
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_BACKEND_BASE
        fromService:
          name: agent-mira-backend
          type: web
          property: url
